CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(128)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

CREATE TABLE devices
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(256)                            NOT NULL,
    user_id BIGINT,
    status  VARCHAR(255),
    CONSTRAINT pk_devices PRIMARY KEY (id)
);

ALTER TABLE devices
    ADD CONSTRAINT FK_DEVICES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

INSERT INTO users(username, password, created_at)
VALUES ('paparacia', '2442', '2023-03-20 14:30:45.120'),
       ('starkoracia', '244268', '2023-03-20 14:30:45.100');

INSERT INTO devices(name, status, user_id)
VALUES ('Test_Device_1', 'NEW', 1),
       ('Test_Device_2', 'NEW', 2);